name: Provisionamento dos recursos

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3       

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3  

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./infra

      - name: Executar Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra